### ISSUE TITLE
conf_client.yml not found dashboard error

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/docker-manager#4]
User submitted this issue on discord:
![image](https://github.com/hummingbot/docker-manager/assets/93164135/6a5b7a24-8233-475d-bf24-46ed817888cd)

The configuration is mistakenly created under the `<bot_instance>/master_bot_conf/` directory instead of being directly under `<bot_instance>/`

**Comment by fengtality** [comment]
I think this is fixed by this PR: https://github.com/hummingbot/dashboard/pull/59

**Comment by MementoRC** [comment]
As a standalone package, it seems that docker-manager should also implement the correct behavior
